tech: Extensive refactor interface for modern swift concurrency (#11)
* tech: Refactor for Swift concurrency (#10)
* tech: Set min iOS target to 13.0 & macOS to 12.0
* docs: Add doc file references to Xcode project
* tech: Update MockServer to be an actor
* chore: Change to use updated package API
* chore: Improve build_xcframework script
* tech: Refactor project to expose more of pact_ffi
* chore: Bump platform versions
* tech: Remove MockServerError and move TransferProtocol
   This PR removes the old MockServerError and moves (nests)
   the TransferProtocol type into the MockServer
* tech: Move generate funcs out of MockServer
* tech: Refactor error messages on failure
* tech: Remove Matcher implementations
* tech: Add binary file body support
* tech: Add support for getting TLS cert
* tech: Remove binary body methods
   This code was likely to be unsafe and unstable.
* tech: Add tests for Pact & Interaction
* chore: Remove dead code
* tech: Make Generate public
* tech: Add more HTTP methods
* tech: Add matcher DSL
* tech: Add more generators and matchers
* tech: Add more matchers
* tech: Move matchers to PactSwift
* tech: Move ProviderState back
* tech: Update docs for withMetadata
* tech: Make initialise a public function
* tech: ProviderState is ExpressibleByStringLiteral
* chore: Fix whitespace/indentation
* tech: Refactor logging
   Previously the logging methods were on the Pact class, now
   they have been moved to their own "namespace" (aka enum).
* tech: Clean up logic with defer
* chore: Update xcframework
* tech: Remove unused MatcherDefinition
* chore: Update test for Pact.version
* chore: Update xcfilelist
* chore: Resolve swiftlint issues
* tech: Remove PactFileManager
* chore: Increase concurrency logging
* tech: Mark types as Sendable
* tech: Make logging initialisation explicit
* tech: Reduce Logging API surface area
* tech: Remove dead code and improve docs
* tech: Add support for adding test name metadata
* chore: Update xcframework
* Update rust reference module to 0.4.19
* Update github workflow for macOS 13 and macOS 14
* Update target configuration and module
   Improving the build_rust_dependencies to set 'MACOSX_' and 'IPHONEOS_DEPLOYMENT_TARGET'
   when building libpact_ffi.a binaries. This removes the ld: warnings stating
   the binary was built for newer targets than being linked.
* Fix build configurations
* tech: Update Package.swift
---------
Co-authored-by: Oliver Jones <oliver@deeperdesign.com>

* tech: Build libpact_ffi with min os version removing "complied for" warnings
* Update XCFramework for libpact_ffi 0.4.19
* tech: Update scripts to test on arm64 and x86_64
* tech: Improve build_test script
* ci: Codecov configuration

diff --git a/Support/build_test b/Support/build_test
--- a/Support/build_test
+++ b/Support/build_test
@@ -19,12 +19,64 @@
 
 set -euo pipefail
 
-SCHEME=${SCHEME:-"PactSwiftMockServer-macOS"}
-DESTINATION=${DESTINATION:-"arch=x86_64"}
+SOURCE_DIR="${BASH_SOURCE[0]%/*}"
 
-set -o pipefail && xcodebuild clean test \
-	-project PactSwiftMockServer.xcodeproj \
-	-scheme "$SCHEME" \
-	-destination "$DESTINATION" \
-	GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES \
-	GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcbeautify
+# "import"
+source "$SOURCE_DIR/utils.sh"
+
+# Properties
+SCHEME_TARGET_PAIRS=()
+
+###############
+# "private"
+
+function __buildTestHelp {
+  echo -e "Builds sheme on destinations and runs tests
+
+Usage:
+    build_test [--scheme VAL1 --target VAL2]
+
+Note:
+    Must be provided as pairs with --scheme argument first of the two!
+
+Options:
+    --scheme    Scheme to build and run tests for
+    --target    Target to build for and test with
+"
+}
+
+if [ $# -eq 0 ]; then
+  # CI is setup with a matrix defining SCHEME and DESTINATION env vars
+  SCHEME="${SCHEME:-"PactSwiftMockServer-macOS"}"
+  DEFAULT_DESTINATION="arch=$(uname -m)"
+  DESTINATION="${DESTINATION:-$DEFAULT_DESTINATION}"
+
+  SCHEME_TARGET_PAIRS=("$SCHEME:::$DESTINATION")
+
+else
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      --scheme)
+        SCHEME_TARGET_PAIRS+=("$2:::$4")
+        shift 4
+        ;;
+
+      -h|--help)
+        __buildTestHelp
+        exit
+        ;;
+
+      *)
+        echo -e "***************************\n* Error: Invalid argument.*\n***************************\n"
+        exit 1
+    esac
+  done
+fi
+
+# Run tests
+for INDEX in "${SCHEME_TARGET_PAIRS[@]}"; do
+  SCHEME="${INDEX%%:::*}"
+  TARGET="${INDEX##*::}"
+
+  executeCommand "xcodebuild -project \"PactSwiftMockServer.xcodeproj\" -scheme \"$SCHEME\" -destination \"$TARGET\" -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES build test | xcbeautify"
+done
