tech: [failing on silicon] Builds Rust binaries in Build Phase script

diff --git a/Support/build_rust_universal_dependencies b/Support/build_rust_universal_dependencies
--- a/Support/build_rust_universal_dependencies
+++ b/Support/build_rust_universal_dependencies
@@ -25,9 +25,10 @@ set -euo pipefail
 # Use the release tag for libpact_ffi-vX.X.X found at https://github.com/pact-foundation/pact-reference/releases
 #
 # ### Usage:
-# ./Support/build_rust_dependencies libpact_ffi-v0.0.3
+# ./Support/build_rust_dependencies libpact_ffi-v0.3.1
 #
-# In order to minimise the built binary size update $LIBPACT_FFI_DI/Cargo.toml and append the following:
+# ### Optional:
+# To minimise the built binary size update $LIBPACT_FFI_DI/Cargo.toml and append the following:
 #
 # [lib]
 # crate-type = ["staticlib"]
@@ -39,10 +40,21 @@ set -euo pipefail
 #
 #######################
 
+if [[ -n "${DEVELOPER_SDK_DIR:-}" ]]; then
+	# Assume we're in Xcode, which means we're probably cross-compiling.
+	# In this case, we need to add an extra library search path for build scripts and proc-macros,
+	# which run on the host instead of the target.
+	# (macOS Big Sur does not have linkable libraries in /usr/lib/.)
+	export LIBRARY_PATH="${DEVELOPER_SDK_DIR}/MacOSX.sdk/usr/lib:${LIBRARY_PATH:-}"
+
+	# source: https://github.com/TimNN/cargo-lipo/issues/41#issuecomment-774793892
+fi
+
 WORKSPACE=${GITHUB_WORKSPACE:-$PWD}
 LIBPACT_FFI_DIR="${WORKSPACE}/../pact-reference/rust/pact_ffi"
 CI=${CI:-"false"}
 PACT_FOUNDATION_REPO="https://github.com/pact-foundation/pact-reference.git"
+ACTIVE_ARCH=$(uname -m)
 
 #######################
 # Pre-requisite       #
@@ -51,10 +63,23 @@ PACT_FOUNDATION_REPO="https://github.com/pact-foundation/pact-reference.git"
 # Check whether this script is being run in the right folder
 if [ ! -d "$PWD/PactSwiftMockServer.xcodeproj" ]
 then
-	echo "🚨  Run this from the same folder where your 'PactSwiftMockServer.xcodeproj' lives."
-	echo "⚠️  You are runing it in $PWD"
+	echo "🚨 Run this from the same folder where your 'PactSwiftMockServer.xcodeproj' lives."
+	echo "ℹ You are runing it in $PWD"
 	exit 1
 fi
+
+#######################
+# Functions           #
+#######################
+
+function clonePactFFI {
+	# Move a level up
+	cd ..
+
+	# Clone the pact-foundation/pact-reference repo
+	echo "ℹ Cloning ${PACT_FOUNDATION_REPO} at release tag: $1"
+	git clone --depth 1 -b $1 $PACT_FOUNDATION_REPO
+}
 
 #######################
 # If CI               #
@@ -69,23 +94,26 @@ if [[ "$CI" == true ]]; then
 		echo "Please run something like ./build_rust_dependencies libpact_ffi-vX.X.X"
 		exit 1
 	fi
-
-	# Move a level up
-	cd ..
-
-	# Clone the pact-foundation/pact-reference repo
-	echo "ℹ️ Cloning ${PACT_FOUNDATION_REPO} at tag: $1"
-	git clone --depth 1 -b $1 $PACT_FOUNDATION_REPO
+	clonePactFFI $1
 
 elif [ ! -d "$PWD/../pact-reference" ]; then
-	echo "🚨  Missing pact-foundation/pact-reference repo."
-	echo "⚠️  Make sure you 'git clone ${PACT_FOUNDATION_REPO}' at the same folder level as your PactSwiftMockServer."
-	exit 1
+	# Check whether tag has been provided
+	if [ $# -lt 1 ]; then
+		echo "🚨  Missing libpact_ffi version tag!"
+		echo "Please run something like ./build_rust_dependencies libpact_ffi-vX.X.X"
+		exit 1
+	fi
+	
+	echo "⚠️ Missing pact-foundation/pact-reference repo"
+	echo "ℹ Creating \"../pact-reference\" folder and cloning \"pact-reference\" repo"
+	mkdir -p "$PWD/../pact-reference"
+	clonePactFFI $1
+
 else
-	echo "👍  Project setup seems to be in order."
+	echo "ℹ Project setup seems to be in order."
 fi
 
-echo "ℹ️  Changing location to ${LIBPACT_FFI_DIR}"
+echo "ℹ Changing location to ${LIBPACT_FFI_DIR}"
 cd $LIBPACT_FFI_DIR
 
 #######################
@@ -96,21 +124,27 @@ cd $LIBPACT_FFI_DIR
 
 echo "👮‍♀️  Checking if Rust is installed..."
 if which cargo >/dev/null; then
-	echo "👍  cargo installed"
+	echo "cargo installed"
+	CARGO_DIR=$(dirname "$( which cargo )")
+	PATH=$PATH:$CARGO_DIR
 elif command -v ~/.cargo/bin/cargo &> /dev/null; then
-	echo "👍  cargo installed in ~/.cargo/bin/"
+	echo "cargo installed in ~/.cargo/bin/"
+	CARGO_DIR=$(dirname "$( command -v ~/.cargo/bin/cargo )")
+	PATH=$PATH:$CARGO_DIR
 else
-	echo "🚨  Rust/Cargo not installed"
-	echo "ERROR: cargo is required and is was found on this machine.\nInstall Rust using either homebrew or follow instructions at https://www.rust-lang.org/tools/install"
+	echo "🚨 Rust/Cargo not installed"
+	echo "ERROR: cargo is required and is was found on this machine.\nInstall Rust using either homebrew:"
+	echo "	curl https://sh.rustup.rs -sSf | sh"
+	echo "or follow instructions at https://www.rust-lang.org/tools/install"
  	exit 1
 fi
 
 # Set the nightly toolchain
-echo "⚠️  Installing a nightly toolchain..."
+echo "ℹ Installing a nightly toolchain..."
 rustup install nightly
 rustup toolchain install nightly
 
-echo "⚠️  Setting nightly toolchain as default..."
+echo "ℹ Setting nightly toolchain as default..."
 rustup default nightly-x86_64-apple-darwin
 
 # Add all the required triples
@@ -120,8 +154,12 @@ rustup target add \
 	x86_64-apple-darwin \
 	aarch64-apple-darwin
 
-# Add the nightly toolchain for aarch64-apple-ios-sim (while aarch64-apple-ios-sim is still Tier 3)
-rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
+# Add the nightly toolchain that includes aarch64-apple-ios-sim
+if [[ $ACTIVE_ARCH == "x86_64" ]]; then
+	rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
+else 
+	rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
+fi 
 
 ##############################################
 # Build libpact_ffi binaries                 #
@@ -179,4 +217,5 @@ echo "👍  Copied x86_64-darwin and arm64-darwin fattie."
 # Cleanup             #
 #######################
 
-echo "🎉  All done!"
+echo "👍  Rust binaries for pact-ffi compiled and ready"
+exit 0
